imports:
  commons: commons.yml

services:
  http:
    ProductService:
      auth: true
      base-path: /org/{orgId}
      path-parameters:
        orgId:
          docs: Organization ID
          type: string
      endpoints:
        
        getAllForCloudPartner:
          path: /partner/{partner}/product
          method: GET
          display-name: List all products under the cloud partner
          path-parameters:
            partner:
              docs: Cloud Partner
              type: string
          response: list<commons.WorkloadProduct>
        
        getAll:
          path: /product
          method: GET
          display-name: List all products under the organization
          response: list<commons.WorkloadProduct>
        
        create:
          path: /product
          method: POST
          display-name: Create an Product & List it to the Partner's marketplace.
          request: CreateProductParams
          response: commons.WorkloadProduct
        
        get:
          path: /product/{productId}
          method: GET
          display-name: Get the Product
          path-parameters:
            productId:
              docs: Product ID
              type: string
          response: commons.WorkloadProduct
        
        delete:
          path: /product/{productId}
          method: DELETE
          docs: >-
            Currently only the product with status = "CREATE_PENDING" or
            "CREATE_FAILED" is allowed to be deleted.
          display-name: Delete the product.
          path-parameters:
            productId:
              docs: Product ID
              type: string
          response: string
        
        update:
          path: /product/{productId}
          method: PATCH
          display-name: Currently, only the Fulfillment URL is allowed to update.
          path-parameters:
            productId:
              docs: Product ID
              type: string
          request:
            body: UpdateProductParams
          response: commons.WorkloadProduct
        
        getMeteringDimensions:
          path: /product/{productId}/dimension
          method: GET
          display-name: List the Metering Dimensions of the Product
          path-parameters:
            productId:
              docs: Product ID
              type: string
          response: list<commons.AwsSaasProductDimension>

types:
  CreateProductParams:
    properties:
      externalID: optional<string>
      fulfillmentUrl: optional<string>
      id: optional<string>
      info: optional<commons.ProductInfo>
      name: optional<string>
      organizationID: optional<string>
      partner: optional<string>
      productType: optional<string>
      service: optional<string>
      status: optional<string>
  
  UpdateProductParams:
    properties:
      fulfillmentUrl: string
      id: string
      organizationID: string
